### ISSUE TITLE
Won't download through Twitch: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by HorstRadish** [wideblaze/DigSite#40] opened 2020-02-20 01:13 UTC
I've repeatedly try'd to download the latest version of the pack through Twitch but every time it fails and says "Object reference not set to an instance of an object." what should I do?

**Comment by wideblaze** [comment] 2020-02-21 10:58
Getting multiple reports of this. The issue is with Twitch client. Recommend opening support tix with them. Issue is likely a temporary problem as google searches show issue cropping up from time to time over last couple years. Try again later seems to be easiest option. You can also use multimc instead of twitch.

**Comment by wideblaze** [comment] 2020-02-21 10:58
Work around: https://youtu.be/uvwy2bEN6k8

**Comment by HorstRadish** [comment] 2020-02-21 21:52
Thanks bro!

**Comment by wideblaze** [comment] 2020-02-23 00:52
New reports of this issue have dropped off. I assume Twitch "fixed the glitch." Will close this issue in a week unless new reports come in.

**Comment by wideblaze** [comment] 2020-04-20 14:33
no new reports, I assume this issue may re-appear from time to time since looking at google there is a history of that happening in the past, the above solution resolves.

**Closed as completed by wideblaze** 2020-04-20 14:33 UTC
Labels: work around, resolved
