### ISSUE TITLE
Exception Ticking World near Flame Station

### ISSUE THREAD

**Issue by QyryAsh** [wideblaze/DigSite#20] opened 2019-09-27 00:18 UTC
Hello,

My friends and I have been playing the DigSite mod for a while now, and found that we cannot get close to the Flame Station. Everytime we get close the server crashes and we get the exception Ticking World. 

We have tried updating, and came to the same result, so it was rolled back. I also tried putting a chunk loader down ahead of me, turning on the lasers and increasing the load size to 10 chunks. I wanted to see if loading the chunks was what got the error, but I found that my character has to actually walk close to the Flame station in order to trigger the exception.

(My apologies if that isn't how the chunk loader actually works.)

We have made it to the portal room, but got confused as all the portals seem to be inactive or covered in bedrock, so we opted for walking towards the Flame Site.

Here is the first server crash log:https://pastebin.com/GfQBVYN8

Any ideas what this could be?

**Comment by wideblaze** [comment] 2019-10-10 11:59
sorry for late reply, was out of the country on vacation.

if you are still having this issues you can try the following:

1) update to DigSite 1.0.18 (released yesterday with a number of crash fixes)

if that does not resolve your issue you can also try

2) temp disable mods: vanillafix (attemps to catch crashes but sometime too much), the one probe (seems to have occasional issues with matter overdrive)

let me know, thanks

**Comment by QyryAsh** [comment] 2019-10-10 13:25
No worries! Thank you for getting back to me! I'll try these out, and should the issue persist / other problems arise I'll let you know. Really like your mod, my friends and I really want to complete it.
Thanks again!

**Comment by ehilscher** [comment] 2019-10-12 07:02
I'm having the same problem. I'm running 1.0.18 and my server crashes when I approach The Flame. I've disabled both the one probe and vanillafix, but the same error occurs:

Exception ticking world io.netty.handler.codec.EncoderException: String too big (was 33212 bytes encoded, max 32767)

**Comment by wideblaze** [comment] 2019-10-12 15:53
Hard to know exactly what is happening. I have a guess that it has something to do with matter overdrive cables (but that is just a guess).

There is a potential "if all else fails" fix:

1) Copy (ie backup) the profile before proceeding: 

2) edit <profile directory>/config/forge.cfg

3) change both settings below to true

`    # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=false
`
`
    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=false
`

4) launch modpack and open world

5) if the world opens without a crash. Immediately quit the game and change the above settings back to false and re-launch.

NOTE: there is a slight chance the this could break the pack completely or in a way that requires you to go into creative mode to resolve. So be sure to do step 1. 

If this works for you, I would be extremely interested in knowing if you come across anything that appears to be missing as you continue playing.

**Comment by wideblaze** [comment] 2019-10-12 16:03
Found the following after doing some additional research 

https://www.reddit.com/r/feedthebeast/comments/awpww5/ticking_entity_issue/

`
waig548 1 point 6 months ago
My friend and I also got this issue. After collecting some data, including logging the contents of the packets, we've concluded that some androids from MatterOverdrive that have excessive (like 16k or more) suffixes of colors in their names might've been the cause of it. In the crash report you provided, it said that you also have installed MatterOverdrive, so I would guess this issue is fairly similiar to that. The solution is to remove that entity, which you can use MCEdit to do so if you can acquire its coordinates, or commands that could kill it, or peaceful mode. (Sorry for the grammar if any.)
`

**Comment by ehilscher** [comment] 2019-10-12 19:28
No change with removeErroringEntities=true and removeErroringTileEntities=true.

I found that same comment. If it is an android, it seems to be a specific one whose spawn is triggered by player proximity. There is an android in the first level of The Flame that seems to be a scripted spawn. Is there a command block or something that triggers this spawn that I can use MCEdit to delete? It's kind of a shot in the dark, but I don't have any other ideas.

**Comment by ehilscher** [comment] 2019-10-13 05:12
I've identified the problem as the minecart android "New Android" on level 4 of The Flame. When I inspect the android using MCEdit, the custom name property is set to "§7" repeated 11064 times, followed by "New Android". That amounts to about 33kB of character data, which is more than the max. If I change the custom name to just "New Android", the server no longer crashes. This is most likely the extra name data that waig548 was talking about. The server didn't crash the first few times I visited The Flame and saw this android, so I don't know what caused that extra data to appear.

**Comment by wideblaze** [comment] 2019-10-13 09:35
First of all, thank you so much for going the extra mile to help identify the source of this issue!

I will open a ticket with horizon and attempt to come up with some sort of workaround since matter overdrive releases are few and far between.

As you saw there isn't much going on there, just an android in a minecart with a name tag.

There was a previous issue in the same place when I used CustomNPCs instead. They would glitch out on the minecarts and become "ghost" NPCs that could not be edited or deleted. So I replaced them with normal entities.

**Comment by ryanpineo** [comment] 2019-10-14 16:36
Confirmed same issue for us, renaming the android fixed it

**Comment by wideblaze** [comment] 2019-10-15 13:22
DigSite 1.0.19 Map - Android at flame replaced with a new one. If this crash continues to happen it will be completely removed.

**Comment by wideblaze** [comment] 2019-11-26 15:37
no new reports of this issue for 30 days. patch much have resolved

**Closed as completed by wideblaze** 2019-11-26 15:37 UTC
Labels: bug, mod bug, patched, investigating
